apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  default.conf: |
    server {
      listen 80;
      location /api/ {
        proxy_pass http://api.shop-main.svc.cluster.local/;
      }
      location / {
        return 200 'shop web. try /api/';
      }
    }
