apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - -c
            - |
              psql -h db-0.db -U postgres -c \
                "CREATE TABLE IF NOT EXISTS goods (
                  id serial primary key,
                  title text
                );"
